#!/bin/sh
cd /tmp
rm -rf /tmp/*.m3u
rm -rf /tmp//usr/lib/enigma2/python/Plugins/Extensions/m3u_Pro/m3u_ProM3U/*.m3u
rm -rf /etc/enigma2/*.del > /dev/null
rm -rf /etc/enigma2/*.tv_org
rm -rf /etc/enigma2/*.tv_bak
sleep 1

curl -Lko /tmp/ReMy_XxX.m3u "https://raw.githubusercontent.com/remytr-org/git_git/master/remy_xxx.m3u"

curl -Lko /tmp/XX-PORN-fr.m3u "https://raw.githubusercontent.com/iptv-org/iptv/master/channels/fr.m3u"

curl -Lko /tmp/XXX-PORN-ASTV.m3u "https://raw.githubusercontent.com/iptv-org/iptv/master/channels/cy.m3u"

curl -Lko /tmp/ReMy_Premium.m3u "https://raw.githubusercontent.com/remytr-org/git_git/master/remy_premium.m3u"

curl -Lko /tmp/TURKEY.m3u "https://raw.githubusercontent.com/iptv-org/iptv/master/channels/tr.m3u"

curl -Lko /tmp/ARABIAN.m3u "https://raw.githubusercontent.com/iptv-org/iptv/master/channels/ae.m3u"

curl -Lko /tmp/CHINESS.m3u "https://raw.githubusercontent.com/iptv-org/iptv/master/channels/cn.m3u"

curl -Lko /tmp/GERMAN.m3u "https://raw.githubusercontent.com/iptv-org/iptv/master/channels/de.m3u"

curl -Lko /tmp/GREEK.m3u "https://raw.githubusercontent.com/iptv-org/iptv/master/channels/gr.m3u"

curl -Lko /tmp/INDIAN.m3u "https://raw.githubusercontent.com/iptv-org/iptv/master/channels/in.m3u"

curl -Lko /tmp/IRANIAN.m3u "https://raw.githubusercontent.com/iptv-org/iptv/master/channels/ir.m3u"

curl -Lko /tmp/ITALIAN.m3u "https://raw.githubusercontent.com/iptv-org/iptv/master/channels/it.m3u"

curl -Lko /tmp/ROMANIAN.m3u "https://raw.githubusercontent.com/iptv-org/iptv/master/channels/ro.m3u"

curl -Lko /tmp/RUSSIAN.m3u "https://raw.githubusercontent.com/iptv-org/iptv/master/channels/ru.m3u"

curl -Lko /tmp/UNITED_KINGDOM.m3u "https://raw.githubusercontent.com/iptv-org/iptv/master/channels/uk.m3u"

curl -Lko /tmp/UNITED_AMERICA.m3u "https://raw.githubusercontent.com/iptv-org/iptv/master/channels/us.m3u"

curl -Lko /tmp/MIX.m3u "https://raw.githubusercontent.com/iptv-org/iptv/master/channels/unsorted.m3u"

sleep 1
rm -rf /tmp/iptvm3upro
FILE=/etc/enigma2/bouquets.tv

WGET='wget --no-check-certificate'

if [ `grep "userbouquet.IPTVWORLDUK001.tv" $FILE | wc -l` -gt 0 ]; then
         echo 'Link avilable'
else
         echo 'Create New line'
         echo '#SERVICE 1:7:1:0:0:0:0:0:0:0:FROM BOUQUET "userbouquet.IPTVWORLDUK001.tv" ORDER BY bouquet' >> $FILE
fi
rm -rf IPTV*

cd /tmp
FreeServertmpa=/tmp/freeservra*
FreeServertmpb=/tmp/freeservrb*
FreeServertmpe=/tmp/freeservre*
rm -r -f $IPTV* > /dev/null 2>&1
rm -f $FreeServertmpa > /dev/null 2>&1
rm -f $FreeServertmpb > /dev/null 2>&1
rm -f $FreeServertmpa* $FreeServertmpb*
HTTPSERV70="https://www.iptvm3ulist.com/iptv-european/united-kingdom-iptv-m3u/"
#TEMP
FreeServertmpb70=/tmp/freeservrb70
FreeServertmpb71=/tmp/freeservrb71
FreeServertmpb72=/tmp/freeservrb72
FreeServertmpb73=/tmp/freeservrb73
FreeServertmpb74=/tmp/freeservrb74
#TEMP
FreeServertmpa70=/tmp/freeservra70
FreeServertmpa71=/tmp/freeservra71
FreeServertmpa72=/tmp/freeservra72 
FreeServertmpa73=/tmp/freeservra73
FreeServertmpa74=/tmp/freeservra74
$WGET -O $FreeServertmpa70 $HTTPSERV70 > /dev/null 2>&1
sed -ne '/United Kingdom/ p' $FreeServertmpa70 > $FreeServertmpa73
sed -ne 's#.*href="\([^"]*\)" rel=.*#\1#p' $FreeServertmpa73 > $FreeServertmpb72
head -1 $FreeServertmpb72 > $FreeServertmpa72
$WGET -q -O- --trust-server-names "$(<freeservra72)" --no-check-certificate > $FreeServertmpb72
sed -ne 's#.*href="\([^>]*\)">Download.*#\1#p' $FreeServertmpb72 > $FreeServertmpa74
$WGET -q -O- --trust-server-names "$(<freeservra74)" --no-check-certificate > $FreeServertmpb74
unzip  $FreeServertmpb74 -d  /tmp
cd iptv*
cd *iptv*
cd *IPTV*
cd IPTV*
for a in * ;do
  b=$(echo $a | sed -e 's/[[:blank:]]/_/g' | sed -r 's/[_()]//g');
  if [ -e "$b" ];then
  echo "">/dev/null;
  else
  mv "$a" "$b";
  fi
done 

i=1
for f in *.m3u; do
  mv "$f" "IPTVWORLDUK$(printf "%03d" $i).m3u" 
  i=$((i + 1))
done

F_IN=IPTVWORLDUK001.m3u 
#F_NAME=/tmp/FreeIPTV.name
F_NAME=IPTVFree.name
F_OUT_ALL='/etc/enigma2/userbouquet.IPTVWORLDUK001.tv'
#CLT=`find . -maxdepth 1 -name "IPTVWORLDUK001*" -print`
#echo $CLT
#mv $CLT IPTVFree.m3u  

echo "getting remote file..."
# get remote-file
#wget "$R_M3U" -O $F_IN

echo "parsing channel names..."
#get channel names
grep EXTINF $F_IN| sed -e 's/.*- //' > $F_NAME

echo "reading URLs and replacing colon..."
# read urls and replace ":"
URLS=`grep http $F_IN | sed -e 's/:/%3a/g'`

echo "go trough urls and creating bouqet..."
# go trough urls and create bouqet
echo "#NAME IPTVWORLDUK001" > $F_OUT_ALL
CNT=0
for u in $URLS; do
CNT=$(($CNT + 1))
NAM=`head -n $CNT $F_NAME | tail -1`
SRV=` printf "%x" $(echo $u | sed -e 's/.*//' -e 's/\l\n//')`
echo "#SERVICE 4097:0:1:$SRV:0:0:0:0:0:0:$u:$NAM" >> $F_OUT_ALL
sed -i 's/:#EXTINF:.*,/#DESCRIPTION: /g' $F_OUT_ALL
sed -i 's#-1,# #g' $F_OUT_ALL
sed -i 's#https://flylinks.net,# #g' $F_OUT_ALL
done

#### EDit By RAED To DreamOS OE2.5/2.6
$WGET -q -O - http://root%s@127.0.0.1/web/servicelistreload?mode=0 && sleep 2
#### End Edit

rm $F_NAME
rm -f $FreeServertmpa 
rm -f $FreeServertmpb 
echo "";

sleep 2;

exit 0