#!/bin/sh
curl https://github.com/popking159/softcam/raw/master/SoftCam.Key -Lko /etc/tuxbox/config/SoftCam.Key
curl https://github.com/popking159/softcam/raw/master/SoftCam.Key -Lko /etc/tuxbox/config/oscam-emu/SoftCam.Key
curl https://github.com/popking159/softcam/raw/master/SoftCam.Key -Lko /etc/tuxbox/config/ncam/SoftCam.Key
exit 0