#!/bin/sh
opkg remove enigma2-plugin-softcams-remy-openatv-softcampanel
opkg update
wget -O - -q http://updates.mynonpublic.com/oea/feed | bash >/dev/null 2>&1
sleep 1
opkg update
sleep 1
opkg install enigma2-plugin-softcams-oscam-emu-ipv4only
opkg install enigma2-plugin-softcams-ncam-ipv4only
opkg install enigma2-plugin-softcams-cccam
mv /usr/bin/oscam-emu /usr/bin/oscam
rm -rf /etc/tuxbox/config/oscam-emu  >/dev/null 2>&1
rm -rf /etc/tuxbox/config/ncam  >/dev/null 2>&1
rm -rf /etc/init.d/softcam.ncam  >/dev/null 2>&1
rm -rf /etc/init.d/softcam.oscam-emu  >/dev/null 2>&1
rm -rf /etc/init.d/softcam.CCcam  >/dev/null 2>&1
curl https://github.com/remytr-org/git_git/raw/master/softcam.Oscam -Lko /etc/init.d/softcam.Oscam >/dev/null 2>&1
curl https://github.com/remytr-org/git_git/raw/master/softcam.Ncam -Lko /etc/init.d/softcam.Ncam  >/dev/null 2>&1
curl https://github.com/remytr-org/git_git/raw/master/softcam.CCcam -Lko /etc/init.d/softcam.CCcam  >/dev/null 2>&1
chmod 755 /etc/init.d/softcam.Oscam
chmod 755 /etc/init.d/softcam.Ncam
chmod 755 /etc/init.d/softcam.CCcam
curl https://github.com/remytr-org/git_git/raw/master/oscam.conf -Lko /etc/tuxbox/config/oscam.conf >/dev/null 2>&1
curl https://github.com/remytr-org/git_git/raw/master/oscam.srvid2 -Lko /etc/tuxbox/config/oscam.srvid2 >/dev/null 2>&1
curl https://github.com/remytr-org/git_git/raw/master/oscam.dvbapi -Lko /etc/tuxbox/config/oscam.dvbapi >/dev/null 2>&1
curl https://github.com/remytr-org/git_git/raw/master/oscam.server -Lko /etc/tuxbox/config/oscam.server >/dev/null 2>&1
curl https://github.com/remytr-org/git_git/raw/master/oscam.user -Lko /etc/tuxbox/config/oscam.user >/dev/null 2>&1
curl https://github.com/remytr-org/git_git/raw/master/oscam.ccache -Lko /etc/tuxbox/config/oscam.ccache >/dev/null 2>&1
curl https://github.com/remytr-org/git_git/raw/master/ncam.conf -Lko /etc/tuxbox/config/ncam.conf >/dev/null 2>&1
curl https://github.com/remytr-org/git_git/raw/master/ncam.srvid2 -Lko /etc/tuxbox/config/ncam.srvid2 >/dev/null 2>&1
curl https://github.com/remytr-org/git_git/raw/master/ncam.user -Lko /etc/tuxbox/config/ncam.user >/dev/null 2>&1
curl https://github.com/remytr-org/git_git/raw/master/ncam.dvbapi -Lko /etc/tuxbox/config/ncam.dvbapi >/dev/null 2>&1
curl https://github.com/remytr-org/git_git/raw/master/ncam.server -Lko /etc/tuxbox/config/ncam.server >/dev/null 2>&1
curl https://github.com/remytr-org/git_git/raw/master/ncam.ccache -Lko /etc/tuxbox/config/ncam.ccache >/dev/null 2>&1
curl https://github.com/MOHAMED19OS/SoftCam_Emu/raw/main/Enigma2/SoftCam.Key -Lko /etc/tuxbox/config/SoftCam.Key >/dev/null 2>&1
/usr/bin/oscam -b -c /etc/tuxbox/config
killall -9 enigma2
