#!/bin/sh
echo "  *ReMy_TeaM_EXTRA_PLUGINS_TEST*"
echo "  *KULLANICILARIN ACIL IHTIYACLARI ICIN ANLIK OLARAK KULLANILACAKTIR*"
sleep 3
echo "  *ILETISIM: enigma2_teknik_servis@hotmail.com*"
echo "  https://remyteam-org.github.io/enigma_turk_team"
echo "  https://www.youtube.com/watch?v=cvkdGrSfMTc"
sleep 12