#!/bin/sh
echo "  *ReMy_TeaM_EXTRA_PLUGINS_TEST*"
echo "  *KULLANICILARIN ACIL IHTIYACLARI ICIN ANLIK OLARAK KULLANILACAKTIR*"
sleep 5
*ILETISIM: enigma2_teknik_servis@hotmail.com*
       * ®ReMy EnigmaTurk TeaM *
https://remyteam-org.github.io/enigma_turk_team
https://www.youtube.com/watch?v=cvkdGrSfMTc
sleep 12