#!/bin/sh
opkg remove enigma2-plugin-extensions--turkvod
curl https://github.com/remytr-org/git_git/raw/master/enigma2-plugin-extensions-turkvod_12.00_openatv_7.ipk -Lko /tmp/enigma2-plugin-extensions-turkvod_12.00_openatv_7.ipk > /dev/null
opkg --force-overwrite install /tmp/enigma2-plugin-extensions-turkvod_12.00_openatv_7.ipk
opkg install --force-reinstall --force-depends /tmp/enigma2-plugin-extensions-turkvod_12.00_openatv_7.ipk
echo ""
echo "    ***  TURKVODA GIRINCE SARI TUSA BASINIZ ***"
sleep 2
killall -9 enigma2