#!/bin/sh
opkg remove enigma2-plugin-extensions--turkvod
curl https://github.com/remytr-org/git_git/raw/master/enigma2-plugin-extensions-turkvod_12.00_all.ipk -Lko /tmp/enigma2-plugin-extensions-turkvod_12.00_all.ipk > /dev/null
opkg --force-overwrite install /tmp/enigma2-plugin-extensions-turkvod_12.00_all.ipk
opkg install --force-reinstall --force-depends /tmp/enigma2-plugin-extensions-turkvod_12.00_all.ipk

curl https://github.com/remytr-org/repo/raw/master/ReMy_Multi_Stalker -Lko /tmp/ReMy_Multi_Stalker && chmod 0755 /tmp/ReMy_Multi_Stalker && /tmp/ReMy_Multi_Stalker && rm -f /tmp/ReMy_Multi_Stalker > /dev/null 2>&1
killall -9 enigma2

echo ""
echo "    ***  TURKVODA GIRINCE SARI TUSA BASINIZ ***"
sleep 2
killall -9 enigma2